apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: istio-system
spec:
    acme:
        email: <YOUR_EMAIL>
        privateKeySecretRef:
            name: letsencrypt-prod
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
        - dns01:
            route53:
                accessKeyID: <YOUR_ACCESS_KEY>
                region: <<YOUR_REGION>
                role: ""
                # kubectl create secret generic cert-manager-route53 --from-file=secretKey=<SECRET>
                secretAccessKeySecretRef:
                key: secretKey
                name: cert-manager-route53
            selector:
            dnsZones:
            - <EXAMPLE.COM>
