apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: <CERTIFICATE_NAME>
  namespace: istio-system
spec:
  secretName: <SECRET_WHICH_STORES_CERT>
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  #commonName is deprecated but can still be set if you like
  commonName: "example.com"
  dnsNames:
  # Make sure to put in every DNS entry, subdomains, wildcards etc.
  - "example.com"
  - "live.example.com"
  - "*.live.example.com"
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
    # Put alle domains from above also in here
        - "example.com"
        - "live.example.com"
        - "*.live.example.com"